#' Get point estimates from model
#'
#' @description
#' Generate point estimates from a dose response curve.
#'
#' @param dataset A dataframe used to generate `model`.
#' @param model A drm model, generated by `modelcomp()` or `drm()`.
#' @param EDx Numeric. The effect level(s) to estimate, given as a proportion
#'  between 0 and 1, so `0.5` requests the EC50. Defaults to 0.5. Note that
#'  `drc::ED()` expects a percentage under `type = "relative"`; the conversion
#'  is handled here, so pass a proportion regardless of `type`.
#' @param interval Character. Method for calculating confidence intervals
#'  of EDx. Choices: `"tfls"`, `"fls"`, `"delta"`, `"none"`. Defaults
#'  to "tfls". See `drc::ED()` for more information.
#' @param level Numeric. Confidence level for the interval calculation.
#'  Defaults to 0.95.
#' @param type Character. `"relative"` expresses `EDx` as a fraction of the
#'  range between the fitted limits, so `EDx = 0.5` is the concentration
#'  halfway down the curve. `"absolute"` treats `EDx` as a value on the
#'  response scale itself, which is only meaningful when the response is on a
#'  bounded scale such as a proportion. Defaults to relative, matching
#'  [toxdrc_modelling()].
#' @param list_obj Optional. List object used for integration with
#'  [runtoxdrc()].
#' @param quiet Logical. Indicates if results should be hidden. Defaults
#'  to FALSE.
#' @param EDargs.supplement List. Optional user-supplied list of additional arguments
#'  compatible with `drc::ED()`.
#'
#' @returns A dataframe of the point estimates. If `list_obj` is provided, returns
#'  this within a list as `list_obj$effectmeasure`.
#'
#' @importFrom drc ED
#'
#' @export
#'
#' @seealso [modelcomp()] to fit the model, and [drc::ED()] for the
#'  underlying estimation.
#'
getECx <- function(
  dataset,
  model,
  EDx = 0.5,
  interval = c("tfls", "fls", "delta", "none"),
  level = 0.95,
  type = c("relative", "absolute"),
  quiet = FALSE,
  EDargs.supplement = list(),
  list_obj = NULL
) {
  interval <- match.arg(interval)
  type <- match.arg(type)

  check_number(EDx, "EDx", min = 0, max = 1, allow_vector = TRUE)
  check_number(level, "level", min = 0, max = 1)
  check_flag(quiet, "quiet")
  check_list_obj(list_obj)

  if (!is.list(EDargs.supplement)) {
    toxdrc_abort(
      c(
        "`EDargs.supplement` must be a named list.",
        "x" = paste0(
          "Received an object of class <",
          class(EDargs.supplement)[1],
          ">."
        ),
        "i" = "Example: EDargs.supplement = list(reference = \"control\")."
      ),
      class = "bad_edargs"
    )
  }

  if (is.null(model)) {
    # runtoxdrc() reaches here when no model could be fitted for a subset.
    # Returning the empty frame keeps the output shape consistent.
    EDdf <- empty_ecx(EDx)

    if (is.null(list_obj)) {
      return(EDdf)
    }

    list_obj$effectmeasure <- EDdf
    return(list_obj)
  }

  if (!inherits(model, "drc")) {
    toxdrc_abort(
      c(
        "`model` must be a fitted drc model.",
        "x" = paste0("Received an object of class <", class(model)[1], ">."),
        "i" = "Models are produced by modelcomp() or drc::drm()."
      ),
      class = "bad_model"
    )
  }

  # drc::ED() interprets respLev differently depending on `type`. For
  # "relative" it is a PERCENTAGE of the range between the fitted limits, so
  # the EC50 is requested as 50. For "absolute" it is a value on the response
  # scale, so 0.5 means a response of 0.5.
  #
  # toxdrc takes EDx as a proportion throughout: it is documented as one,
  # validated between 0 and 1, and labelled as one, since the output column
  # says EC50 for EDx = 0.5. Passing 0.5 straight through under the default
  # relative type therefore asked drc for the EC0.5, roughly a hundredfold
  # lower concentration, and labelled the answer EC50.
  resp_lev <- if (identical(type, "relative")) EDx * 100 else EDx

  # Build argument list for ED()
  EDargs <- c(
    list(
      object = model,
      respLev = resp_lev,
      interval = interval,
      level = level,
      type = type,
      display = !quiet
    ),
    EDargs.supplement
  )

  # Safely run ED() and capture output
  EDvals <- tryCatch(
    suppressWarnings(do.call(ED, EDargs)),
    error = function(e) return(NULL)
  )

  # Handle failed fit or NA result. This previously returned the placeholder
  # frame unconditionally, so a pipeline run that supplied list_obj received a
  # data frame where it expected a list.
  if (is.null(EDvals)) {
    EDdf <- empty_ecx(EDx)

    if (!quiet) {
      message(
        "ED() could not estimate the requested effect level(s); ",
        "returning NA estimates."
      )
    }

    if (is.null(list_obj)) {
      return(EDdf)
    }

    list_obj$effectmeasure <- EDdf
    return(list_obj)
  }

  ## --- Clean and format output --- ##

  # Convert to data frame, preserving numeric types
  EDdf <- as.data.frame(EDvals, stringsAsFactors = FALSE)

  # Label from EDx rather than from ED()'s rownames. The rownames carry
  # whatever was passed as respLev, which is a percentage under the relative
  # type and a response value under the absolute one, so deriving the label
  # from them means it changes meaning with `type`. EDx is a proportion in
  # both cases, which is what the EC label denotes. Row order follows the
  # order of respLev, so the two line up.
  EDdf$`Effect Measure` <- paste0("EC", EDx * 100)

  # Reorder columns (Effect Measure first)
  EDdf <- EDdf[, c(
    "Effect Measure",
    names(EDdf)[names(EDdf) != "Effect Measure"]
  )]

  # Ensure missing columns (Lower/Upper) exist if interval = "none"
  expected_cols <- c("Estimate", "Std. Error", "Lower", "Upper")
  missing_cols <- setdiff(expected_cols, names(EDdf))
  if (length(missing_cols) > 0) {
    EDdf[missing_cols] <- NA
  }

  rownames(EDdf) <- NULL

  # Print if requested
  if (!quiet) {
    print(EDdf)
  }

  ## --- Combine or return --- ##
  if (is.null(list_obj)) {
    return(EDdf)
  }

  list_obj$effectmeasure <- EDdf
  list_obj
}
