#' Get ECx estimates from model
#'
#' @param dataset A dataframe.
#' @param model A drm model, generated by `modelcomp()` or `drm()`.
#' @param EDx The effect measure of interest (i.e. 0.5 for EC50)
#' @param metadata Optional. Generated by getmetadata.
#' @param list_obj Optional. Used for integration with `runtoxdrc`.
#' @param interval Character. Method for calculating confidence intervals of EDx. Choices: `"tfls"`, `"fls"`, `"delta"`, `"none"`. Default: "tfls".
#' @param level Numeric. Confidence level for the interval calculation. Default: 0.95.
#' @param type Character. Whether EDx is calculated as `"absolute"` or `"relative"`. Default: "absolute".
#' @param quiet Logical. Whether EDx results should be printed. Default: FALSE.
#' @param EDargs.supplement List. Optional user-supplied list of additional or overriding ED arguments. Can include `interval`, `level`, `type`, or other arguments compatible with `drc::ED()`.

#'
#'
#' @returns If list_obj is not provided, returns estimate. If list object is provided, list_obj$results stores a dataframe with the ECx estimates.
#' @importFrom drc ED
#' @export

getECx <- function(
  dataset,
  model,
  EDx = 0.5,
  interval = c("tfls", "fls", "delta", "none"),
  level = 0.95,
  type = c("absolute", "relative"),
  quiet = FALSE,
  EDargs.supplement = list(),
  metadata = NULL,
  list_obj = NULL
) {
  EDargs <- list(
    respLev = EDx,
    object = model,
    interval = match.arg(interval),
    level = level,
    type = match.arg(type),
    display = !quiet
  )

  EDvals <- tryCatch(
    suppressWarnings(do.call(ED, EDargs)),
    error = function(e) {
      return(rep(NA, 4))
    }
  )

  #estimate names need to generate automatically from legnth of EDx vector.
  #For each entry, give ECx + std.error_(ECx). If interval in list, also have 95u_ecx and 95lECx.
  #in vector form, gives all EC50s, then all std errs, etc.

  estimate_names <- c(
    paste0("EC", EDx * 100),
    "Std. Error",
    "Lower95",
    "Upper95"
  )

  names(EDvals) <- estimate_names
  EDvals <- as.data.frame(t(EDvals))

  if (!quiet) {
    print(EDvals)
  }

  if (is.null(list_obj)) {
    return(EDvals)
  }

  if (!is.null(list_obj)) {
    if (!is.list(list_obj)) {
      stop("Provided list_obj must be a list.")
    }

    if (is.null(metadata)) {
      results <- EDvals
    } else {
      results <- cbind(metadata, EDvals)
    }
    list_obj$results <- results
    return(list_obj)
  }
}
